name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.x
    - name: Install CI dependencies
      run: pip install tox==3.23.0
    - name: Run Tests via Tox
      run: tox